#WRITE A FUNCTION TO READ THE CONTENTS OF THE WORDBANK.TXT
#FILE AND RANDOMLY SELECT ONE OF THE WORDS. 
#THE SELECTED WORD SHOULD BE RETURNED AND USED IN THE GAME.

#RETURNS THE CHOSEN STRING
def Choose():
    selectedWord = ""
    readFile()
    
    #Your code here


    return

#READ THE CONTENTS OF WORDBANK.TXT AND RETURN AN ARRAY
#OF STRINGS TO CHOOSE FROM.
def readFile():
    

    return

